### ISSUE TITLE
ProsemirrorEditor.svelte CSS Warnings.

### ISSUE THREAD

**Issue by michaelcuneo** [christianheine/prosemirror-svelte#4]
When I install this for Svelte 3.17.3 ... I get a lot of CSS selector warnings pointing at ProsemirrorEditor.svelte

```
node_modules/prosemirror-svelte/ProsemirrorEditor.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
Unused CSS selector ":global(.ProseMirror) li" (136:2)
134:   }
135:
136:   :global(.ProseMirror) li {
       ^
137:     position: relative;
138:   }
node_modules/prosemirror-svelte/ProsemirrorEditor.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
Unused CSS selector ":global(.ProseMirror) pre" (132:2)
130:   }
131:
132:   :global(.ProseMirror) pre {
       ^
133:     white-space: pre-wrap;
134:   }
• client
node_modules/prosemirror-svelte/ProsemirrorEditor.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
Unused CSS selector ":global(.ProseMirror) li" (136:2)
134:   }
135:
136:   :global(.ProseMirror) li {
       ^
137:     position: relative;
138:   }
node_modules/prosemirror-svelte/ProsemirrorEditor.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
Unused CSS selector ":global(.ProseMirror) pre" (132:2)
130:   }
131:
132:   :global(.ProseMirror) pre {
       ^
133:     white-space: pre-wrap;
134:   }
> Listening on http://localhost:3000
✔ service worker (756ms)
✔ service worker (13ms)

```

**Comment by christianheine** [comment]
Hm. These selectors are used internally by Prosemirror. 

The reason that they are there in the first place is to avoid having to import the mandatory CSS for Prosemirror (https://prosemirror.net/docs/ref/#view) by some other means. In its current form, the component is ready-to-use.

Since they are created dynamically, Svelte won't find them at compile-time. So they can be safely ignored (or disabled like this: https://stackoverflow.com/questions/60677782/how-to-disable-svelte-warning-unused-css-selector), but I have to admit that this is less than ideal. 

To be honest. Not sure how to address this in a better way. I'm open for suggestions.
